### PR TITLE
Upgrade to latest LTS, clean up stack.yaml

### PR DESCRIPTION
**Pull request by mihaimaruseac**
This brings up a more modern compiler, which will be useful for next PR changes I am planning.

### CODE REVIEW

**Comment by spamegg1** [comment]
Cool, do you think it would be possible to setup automated testing of PRs with Travis CI or AppVeyor or something like that in the future? I tried Travis on my own fork and it worked fine.

**Comment by mihaimaruseac** [comment]
I could try sending a PR to set-up GitHub actions to set CI up.

**Comment by mihaimaruseac** [comment]
CI done in #18

**Comment by RationalAsh** [comment]
Hey great effort with the CI, been meaning to do it but never got around to it. Much appreciated!

**Pull request merged**
